#!/usr/bin/env bash
if [ -e /opt/net-gargoyle/workspace/cycle.py ]; then
  echo "Existing script found at /opt/net-gargoyle/workspace/cycle.py"
  exit 0
else
  echo "Installing honey cycle"
fi
echo -e "$(date +%Y%m%d%H%M%S) >>> \e[1;33m  ---> Starting install run for \e[0;32m honey\e[1;38m cycle \e[0m  " | tee /var/log/honey_cycle.dat
mkdir /var/tmp/hcint 2>/dev/null
cd /var/tmp/hcint || exit 1
rm -rf ./*
git clone https://github.com/jpegleg/net-gargoyle2 || exit 1
cd net-gargoyle2
chmod +x install
./install
cd ..
git clone https://github.com/jpegleg/honey-cycle
cd honey-cycle
cp cycler.py /opt/net-gargoyle/workspace/
cp honey-cycle /usr/local/sbin/
chmod +x /usr/local/sbin/honey-cycle
cp honey.service /usr/lib/systemd/system/honey.service
systemctl enable /usr/lib/systemd/system/honey.service
cd /var/tmp/
rm -rf /var/tmp/hcint
echo -e "$(date +%Y%m%d%H%M%S) >>> \e[1;33m Ending install run for \e[1;39m honey\e[1;36m cycle \e[0m" | tee /var/log/honey_cycle.dat
